name: NodeJS with Webpack

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Restore pnpm cache
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Fallback install pnpm if missing
      run: |
        if ! command -v pnpm; then
          npm install -g pnpm
        fi

    - name: Check for pnpm-lock.yaml
      run: |
        if [ ! -f pnpm-lock.yaml ]; then
          echo "WARNING: pnpm-lock.yaml not found in repo root!"
        fi

    - name: Debug pnpm install
      run: |
        echo "PATH=$PATH"
        which pnpm
        pnpm --version || echo "pnpm not found"

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build

    - name: Save pnpm cache
      if: github.event_name != 'pull_request'
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
